### ISSUE TITLE
toLabel and itemHtml are contradicting.

### ISSUE THREAD

**Issue by sporto** [sporto/elm-select#22]
There are two ways to display an item.

**toLabel**

```
Select.newConfig OnSelect .label
```

**withItemHtml**

```
Select.withItemHtml (\i -> Html.li [] [ text i ]) config
```

Even you want `withItemHtml` you still need to provide the label function. This feels ugly. Probably fix by asking for a function that converts the item to html directly in `Select.newConfig`

**Comment by zgohr** [comment]
Are you talking something like this? `Select.newConfig OnSelect .label (Html.text << .label)`

The reason I didn't touch `toLabel` when I added `withItemHtml` is because the former is still used during the search function. So even if you want to display the item differently, search still needs to know what string to search on.

Let me know how you want this resolved and I can make a PR.

**Comment by sporto** [comment]
I don't know how to improve this tbh, both `toLabel` and `withItemHtml` are needed at different points. Doesn't seem that we can just have one way or the other. Maybe just adding more documentation to make this clear.

**Comment by jaredramirez** [comment]
A pattern that I've found helpful that might be useful here is:
```elm
type DisplayType msg item = Label (item -> String) | Html (item -> Html msg)

type alias RequiredConfig msg item =
    { onSelect : Maybe item -> msg
    , display : DisplayType msg item
    , filter : String -> List item -> Maybe (List item)
    }

label : (item -> String) -> DisplayType msg item
label = Label

htmlItem : (item -> Html msg) -> DisplayType msg item
htmlItem = Html
```

Then you can expose `label, htmlItem, DisplayType` to keep the custom type private. This'll let the user decide which method they want to go and demonstrates that they are mutually exclusive. The biggest con I see is that it'd be a major version bump.
