### ISSUE TITLE
Form submitted when pressing Enter (selecting an item)

### ISSUE THREAD

**Issue by rlopzc** [sporto/elm-select#42]
If the select is wrapped in a `Html.form` then the form is submitted whenever the user hits enter to select an item (using the keyboard)

**Comment by sporto** [comment]
I'm not convinced that this is wrong. Hitting enter in inputs and submitting a form because of that is the standard browser behaviour. Do you have another inputs in the form? What do you expect to happen when you hit enter there? Maybe the form shouldn't use `onSubmit` or maybe it should have `onPreventDefault` in the form. Let's discuss

**Comment by rlopzc** [comment]
When I hit enter, I expect the same behavior as the Html select element inside a form, which is just to select the item and not submit the form.
Is the default behavior in other input elements but not in a select as sibling of the inputs.

Using `onPreventDefault` changes something in the logic of all the interactions in the select behavior?

Small test:
```html
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
</head>

<body>
    <form onsubmit="alert('submitted');">
        <input type="text">
         <select>
          <option value="volvo">Volvo</option>
          <option value="saab">Saab</option>
          <option value="mercedes">Mercedes</option>
          <option value="audi">Audi</option>
        </select>

        <input type="submit" />
    </form>
</body>
```

Hit enter on the field, it gets submitted. Go to the select and hit enter or change the option and the form will not be submitted.

**Comment by sporto** [comment]
Make sense, thanks
